'use client';

import type { Metadata } from 'next';
import { useEffect } from 'react';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

// Metadata object is not valid in a client component.
// We can remove it or handle it differently if needed,
// but for now, we'll focus on fixing the hydration error.
// export const metadata: Metadata = {
//   title: 'OrgConnect',
//   description: 'Generated by Firebase Studio',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // This effect runs only on the client, after hydration
    document.documentElement.classList.remove('no-touch');
  }, []);

  return (
    <html lang="fa" dir="rtl" className="no-touch">
      <head>
        <title>OrgConnect</title>
        <meta name="description" content="Generated by Firebase Studio" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={cn('font-body antialiased')}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
